sequenceDiagram
participant yd as qrexec-daemon (domY)
participant xd as qrexec-daemon (domX)
participant 0c as qrexec-client
participant ya as domY qrexec-agent
participant xa as domX qrexec-agent
# qrexec-client-vm invoked, qrexec-agent generates req_id
ya ->> yd: msg trigger service params + req_id
Note over yd: checks policy
yd ->> 0c: exit code
0c -->> xd: (if policy allows) connects
xd ->> 0c: MSG_HELLO + peer_info
0c ->> xd: MSG_HELLO + peer_info
0c ->> xd: MSG_EXEC_CMDLINE + exec_params
xd ->> 0c: MSG_EXEC_CMDLINE + exec_params, empty cmd
xd ->> xa: MSG_EXEC_CMDLINE + exec_params
0c --x xd: disconnects
0c -->> yd: connection starts
0c ->> yd: MSG_HELLO + peer_info
yd ->> 0c: MSG_HELLO + peer_info
0c ->> yd: MSG_SERVICE_CONNECT + exec_params (cmd = req_id)
0c --x yd: connection ends
yd ->> ya: MSG_SERVICE_CONNECT + exec_params (cmd = req_id)
ya ->> ya: vchan server waits
xa --> ya: connection established
# qrexec-agent now plays role of qrexec-client in dom0-based example (see above)
