graph LR
subgraph someVM
A[qrexec-agent]
end
subgraph dom0
C[qrexec-client]
B[qrexec-daemon]
C -->|initial request| B
B -->|relayed request| A
B -. vchan details .-> C
B -. vchan details .-> A
end
C -->|established vchan channel| A
